create table admissiondetails(
	admission_no int unique,
	Student_FN varchar(50),
	Student_LN varchar(50),
	Father_FN varchar(50),
	Father_LN varchar(50),
	Mother_FN varchar(50),
	Mother_LN varchar(50),
	Email varchar(40),
	Stu_Mobile varchar(10) primary key,
	DOB varchar(15),
	Address varchar(100),
	City varchar(20),
	State varchar(20),
	Zip varchar(10),
	Parent_mob_1 varchar(10),
	Parent_mob_2 varchar(10),
	Course_1 varchar(50),
	Course_2 varchar(50),
	School varchar(50),
	X_Marks int,
	XII_Marks int,
	Cut_off float,
	Hostel_DayScholor varchar(15)
);
